### ISSUE TITLE
[ENH] Todo datafusion planner issues

### ISSUE THREAD

**Issue by ayushdg** [dask-contrib/dask-sql#785]
Followup things to look into post release:

- [ ] Improve function signature handling in the planner
- [ ] Identify why the codebase cannot find column name in backend mapping and return on keyError the column name
- [ ] case when cbo optimizer rule types
- [ ] test and clean schema handling
- [ ] cleanup kwarg handling
